# Generated by Django 3.1.5 on 2021-02-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='firstname',
            field=models.CharField(default='jamsheer', max_length=40),
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='lastname',
            field=models.CharField(default='koniyath', max_length=40),
        ),
    ]
