# Generated by Django 3.1.5 on 2021-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210203_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
